services:
  gnc_sim:
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Force OpenGL to use the NVIDIA GPU instead of CPU/Mesa
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, display, compute, utility]
